# How to Read TSV Dataset using Pandas & Analysis :-

In [3]:
import pandas as pd

In [4]:
orders=pd.read_csv("C:\\Users\\rahul\\OneDrive\\Desktop\\DA Project\\dataset\\chips.tsv",delimiter='\t')

In [5]:
orders.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [6]:
orders.shape

(4622, 5)

In [7]:
orders.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [8]:
orders.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [9]:
orders.item_price.head(10)

0     $2.39
1     $3.39
2     $3.39
3     $2.39
4    $16.98
5    $10.98
6     $1.69
7    $11.75
8     $9.25
9     $9.25
Name: item_price, dtype: object

In [10]:
orders.item_name.str.upper().head(5)

0             CHIPS AND FRESH TOMATO SALSA
1                                     IZZE
2                         NANTUCKET NECTAR
3    CHIPS AND TOMATILLO-GREEN CHILI SALSA
4                             CHICKEN BOWL
Name: item_name, dtype: object

In [11]:
orders.item_name.str.lower().head(5)

0             chips and fresh tomato salsa
1                                     izze
2                         nantucket nectar
3    chips and tomatillo-green chili salsa
4                             chicken bowl
Name: item_name, dtype: object

In [12]:
orders.item_name.str.swapcase().head(5)

0             cHIPS AND fRESH tOMATO sALSA
1                                     iZZE
2                         nANTUCKET nECTAR
3    cHIPS AND tOMATILLO-gREEN cHILI sALSA
4                             cHICKEN bOWL
Name: item_name, dtype: object

# Only show all records start with chicken :-

In [13]:
orders[orders.item_name.str.contains('chicken',case=False)].shape

(1560, 5)

# How to find out Largest & Smallest Price Chicken items :-

In [14]:
orders.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [15]:
orders.item_price[0]

'$2.39 '

In [16]:
orders.item_price

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
         ...
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: object

# How to convert symbol to number and remove space :-

In [17]:
def convert(x):
    r=x.replace('$','').strip()
    r=float(r)
    return r

orders['Price']=orders.item_price.apply(convert)

In [18]:
orders.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price             object
Price                 float64
dtype: object

In [19]:
orders.Price[0]

2.39

In [20]:
orders.item_price[0]

'$2.39 '

In [21]:
orders.head()

,order_id,quantity,item_name,choice_description,item_price,Price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98

# Find maximum Price.

In [22]:
orders.loc[orders[orders.item_name.str.contains("chicken",case=False)].Price.idxmax()]

order_id                                                            511
quantity                                                              4
item_name                                               Chicken Burrito
choice_description    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...
item_price                                                      $35.00
Price                                                              35.0
Name: 1254, dtype: object

# Find minimum Price.

In [23]:
orders.loc[orders[orders.item_name.str.contains("chicken",case=False)].Price.idxmin()]

order_id                                                            479
quantity                                                              1
item_name                                               Chicken Burrito
choice_description    [Fresh Tomato (Mild), [Lettuce, Rice, Fajita V...
item_price                                                       $8.19
Price                                                              8.19
Name: 1161, dtype: object

# How to Find out Missing Records

In [24]:
orders.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
Price                    0
dtype: int64

In [26]:
orders[orders.choice_description.isnull()]

,order_id,quantity,item_name,choice_description,item_price,Price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
6,3,1,Side of Chips,NaN,$1.69,1.69
10,5,1,Chips and Guacamole,NaN,$4.45,4.45
14,7,1,Chips and Guacamole,NaN,$4.45,4.45
...,...,...,...,...,...,...
4600,1827,1,Chips and Guacamole,NaN,$4.45,4.45
4605,1828,1,Chips and Guacamole,NaN,$4.45,4.45
4613,1831,1,Chips,NaN,$2.15,2.15
4614,1831,1,Bottled Water,NaN,$1.50,1.50
4616,1832,1,Chips and Guacamole,NaN,$4.45,4.45

In [28]:
orders.shape

(4622, 6)

In [29]:
orders_new=orders.dropna()

In [30]:
orders_new.shape

(3376, 6)

In [31]:
orders_new.isnull().sum()

order_id              0
quantity              0
item_name             0
choice_description    0
item_price            0
Price                 0
dtype: int64

In [32]:
orders['choice_description'].head()

0                                                  NaN
1                                         [Clementine]
2                                              [Apple]
3                                                  NaN
4    [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
Name: choice_description, dtype: object

In [33]:
orders['choice_description']=orders['choice_description'].map(lambda x: str(x).lstrip('[').rstrip(']'))

In [34]:
orders['choice_description'].head()

0                                                  nan
1                                           Clementine
2                                                Apple
3                                                  nan
4    Tomatillo-Red Chili Salsa (Hot), [Black Beans,...
Name: choice_description, dtype: object

# How to Add a New Column :-

In [35]:
bill = orders.quantity*orders.Price

In [36]:
orders.insert(6,'Total_Bill',bill)

In [37]:
orders.head()

,order_id,quantity,item_name,choice_description,item_price,Price,Total_Bill
0,1,1,Chips and Fresh Tomato Salsa,nan,$2.39,2.39,2.39
1,1,1,Izze,Clementine,$3.39,3.39,3.39
2,1,1,Nantucket Nectar,Apple,$3.39,3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,nan,$2.39,2.39,2.39
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), [Black Beans,...",$16.98,16.98,33.96